DROP TABLE SALES_FACT;
DROP TABLE TR_CUSTOMER;
DROP TABLE TR_STORE;
DROP TABLE TR_SUPPLIER;
DROP TABLE TR_PRODUCT;


CREATE TABLE "TR_STORE"(
"STORE_ID" VARCHAR2(4), 
"STORE_NAME" VARCHAR2(20),
CONSTRAINT STORE_ID_PKID PRIMARY KEY (STORE_ID)
);

CREATE TABLE "TR_SUPPLIER"(
"SUPPLIER_ID" VARCHAR2(5), 
"SUPPLIER_NAME" VARCHAR2(30),
CONSTRAINT SUPPLIER_ID_PKID PRIMARY KEY (SUPPLIER_ID)
);
CREATE TABLE "TR_PRODUCT"(
"PRODUCT_ID" VARCHAR2(6),
"PRODUCT_NAME" VARCHAR2(30),
"PRICE" NUMBER(5,2),
CONSTRAINT PRODUCT_ID_PKID PRIMARY KEY (PRODUCT_ID)
);
CREATE TABLE "TR_CUSTOMER"(
"CUSTOMER_ID" VARCHAR2(4),
"CUSTOMER_NAME" VARCHAR2(30),
CONSTRAINT CUSTOMER_ID_PKID PRIMARY KEY (CUSTOMER_ID)
);
CREATE TABLE "SALES_FACT"(
"STORE_ID" VARCHAR2(5), 
"SUPPLIER_ID" VARCHAR2(5),
"PRODUCT_ID" VARCHAR2(6),
"CUSTOMER_ID" VARCHAR2(4),
"T_DATE" DATE,
"QUANTITY" NUMBER(3,0),
"SALES" NUMBER(5,2),
CONSTRAINT FACT_STORE_ID_FKID FOREIGN KEY (STORE_ID) REFERENCES TR_STORE(STORE_ID),
CONSTRAINT FACT_SUPPLIER_ID_FKID FOREIGN KEY (SUPPLIER_ID) REFERENCES TR_SUPPLIER(SUPPLIER_ID),
CONSTRAINT FACT_PRODUCT_ID_FKID FOREIGN KEY (PRODUCT_ID) REFERENCES TR_PRODUCT(PRODUCT_ID),
CONSTRAINT FACT_CUSTOMER_ID_FKID FOREIGN KEY (CUSTOMER_ID) REFERENCES TR_CUSTOMER(CUSTOMER_ID)
);
