DECLARE
  TYPE COLLECT_TRAN_ATT IS TABLE OF TRANSACTIONS%ROWTYPE;
  TRAN_ATT COLLECT_TRAN_ATT;
--  DEFINE PARAMETERS ACCORDING TO TABLE MASTERDATA
  V_SUPPLIER_NAME MASTERDATA.SUPPLIER_NAME%TYPE :=null;
  V_PRODUCT_NAME MASTERDATA.PRODUCT_NAME%TYPE :=null;
  V_SUPPLIER_ID MASTERDATA.PRODUCT_NAME%TYPE :=null;
  V_PRICE MASTERDATA.PRICE%TYPE :=0;
  V_COUNT numbeR :=0;
  CURSOR GET_TRAN IS
    SELECT * FROM TRANSACTIONS;
BEGIN
  OPEN GET_TRAN;
-- OUTER LOOP
  LOOP
--  PUT 50 DATA FROM TRANSACTIONS TABLE TO TRAN_ATT
    FETCH GET_TRAN
    BULK COLLECT INTO TRAN_ATT LIMIT 50;
    EXIT WHEN GET_TRAN%NOTFOUND;
--    INNER LOOP
    FOR R IN TRAN_ATT.FIRST..TRAN_ATT.LAST LOOP
    SELECT SUPPLIER_NAME,PRODUCT_NAME,SUPPLIER_ID,PRICE  INTO V_SUPPLIER_NAME,V_PRODUCT_NAME,V_SUPPLIER_ID,V_PRICE FROM MASTERDATA WHERE PRODUCT_ID=TRAN_ATT(R).PRODUCT_ID;
--    CHECK IF DATA HAS ALREADY EXISTED IN TABLE CUSTOMER
    SELECT  COUNT(*) INTO V_COUNT FROM  TR_CUSTOMER WHERE CUSTOMER_ID=TRAN_ATT(R).CUSTOMER_ID;
    IF V_COUNT = 0 THEN
--    INSERT NEW DATA INTO TABLE CUSTOMER
    INSERT INTO TR_CUSTOMER VALUES(TRAN_ATT(R).CUSTOMER_ID,TRAN_ATT(R).CUSTOMER_NAME);
    END IF;
--    CHECK IF DATA HAS ALREADY EXISTED IN TABLE STORE
    SELECT  COUNT(*) INTO V_COUNT FROM  TR_STORE WHERE STORE_ID=TRAN_ATT(R).STORE_ID;
    IF V_COUNT = 0 THEN
--    INSERT NEW DATA INTO TABLE STORE
    INSERT INTO TR_STORE VALUES(TRAN_ATT(R).STORE_ID,TRAN_ATT(R).STORE_NAME);
    END IF;
--    CHECK IF DATA HAS ALREADY EXISTED IN TABLE SUPPLIER    
    SELECT  COUNT(*) INTO V_COUNT FROM  TR_SUPPLIER WHERE SUPPLIER_ID=V_SUPPLIER_ID;
    IF V_COUNT = 0 THEN
--    INSERT NEW DATA INTO TABLE SUPPLIER
    INSERT INTO TR_SUPPLIER VALUES(V_SUPPLIER_ID,V_SUPPLIER_NAME);
    END IF;
--    CHECK IF DATA HAS ALREADY EXISTED IN TABLE PRODUCT        
    SELECT  COUNT(*) INTO V_COUNT FROM  TR_PRODUCT WHERE PRODUCT_ID=TRAN_ATT(R).PRODUCT_ID;
    IF V_COUNT = 0 THEN
--    INSERT NEW DATA INTO TABLE PRODUCT
    INSERT INTO TR_PRODUCT VALUES(TRAN_ATT(R).PRODUCT_ID,V_PRODUCT_NAME,V_PRICE);
    END IF;
    
    
--    INSERT NEW DATA INTO TABLE SALES_FACT   
     INSERT INTO SALES_FACT VALUES(TRAN_ATT(R).STORE_ID,V_SUPPLIER_ID,TRAN_ATT(R).PRODUCT_ID,TRAN_ATT(R).CUSTOMER_ID,
     TRAN_ATT(R).T_DATE,TRAN_ATT(R).QUANTITY,V_PRICE*TRAN_ATT(R).QUANTITY);
--    END INNER LOOP
  END LOOP;
--    END OUTER LOOP
  END LOOP;
--  END CURSOR
  CLOSE GET_TRAN;
END;
